from enum import Enum


class Token(Enum):
    ADD = "+"
    SUB = "-"
    MUL = "*"
    DIV = "/"
    EXP = "^"
    MOD = "%"
    NEWL = "\n"
    INT = "int"
    FLOAT = "float"
    BOOL = "bool"
    FALSE = "false"
    TRUE = "true"
    VOID = "void"
    OR = "||"
    AND = "&&"
    EQ = "=="
    NEQ = "!="
    LEQ = "<="
    GEQ = ">="
    LE = "<"
    GE = ">"
    ASSIGN = "="
    OUT = "out"
    COMMA = ","
    IDENTIFIER = "id"
    FUNC = "func"
    LPAREN = "("
    RPAREN = ")"
    LBRACE = "{"
    RBRACE = "}"
    RETURN = "return"
    IF = "if"
    ELIF = "elif"
    ELSE = "else"
